### ISSUE TITLE
数据train2.json不存在

### ISSUE THREAD

**Issue by CynthiaWan007** [0308kkkk/CADA#2]
我在复现您的代码的时候，代码里要求使用train2.json文件，但是您的data数据文件里没有train文件，这是为什么。

**Comment by YanLingLi-AI** [comment]
好的，今晚我抽空发你一下，顺便在github上更新一下

CynthiaWan007 ***@***.***> 于2023年11月1日周三 09:09写道：

**Comment by YanLingLi-AI** [comment]
已分享
